import { ArrowUpRight, CalendarDays, ClipboardCheck, Database, GraduationCap, LayoutDashboard, Search, Settings, ShieldCheck, UserRound, UsersRound } from 'lucide-react'
import { SiteFooter, SiteHeader } from '@/components/site-shell'
import { RotatingHeadline } from '@/components/rotating-headline'

const assets = {
  staffDashboard: '/assets/staff-dashboard.png',
  staffStudents: '/assets/staff-students.png',
  staffResults: '/assets/staff-results.png',
  studentResults: '/assets/student-results.png',
  staffIcon: '/assets/staff-app-icon.png',
  studentIcon: '/assets/student-app-icon.png',
  playstoreStaff: '/assets/playstore-staff-proof.png',
  playstoreStudent: '/assets/playstore-student-proof.png',
}

const Arrow = () => <ArrowUpRight aria-hidden="true" size={16} />
const iconMap = { administration: Database, attendance: UsersRound, results: ClipboardCheck, assessments: GraduationCap }

type Workflow = { key: keyof typeof iconMap; title: string; description: string; rows: string[] }
const workflows: Workflow[] = [
  { key: 'administration', title: 'Administration', description: 'Set up the structure of the school once and keep daily records organised.', rows: ['Student biodata, admissions, classes, and sessions', 'Staff records, subjects, and class assignments'] },
  { key: 'attendance', title: 'Attendance', description: 'Record presence quickly and give school leaders better visibility into daily participation.', rows: ['Student attendance by class', 'Staff attendance and attendance reports'] },
  { key: 'results', title: 'Results & Reports', description: 'Move from raw scores to useful academic reports without rebuilding spreadsheets every term.', rows: ['Score entry, grading, and result checking', 'Bulk result printing and performance reports'] },
  { key: 'assessments', title: 'CBT & Assessments', description: 'Support digital tests and assessment workflows from the same school platform.', rows: ['Computer Based Testing setup and quiz links', 'Score review, approval, and academic record syncing'] },
]

function Button({ children, href = '/contact', light = false }: { children: React.ReactNode; href?: string; light?: boolean }) { return <a className={`button ${light ? 'button-light' : 'button-primary'}`} href={href}>{children}<Arrow /></a> }
function Header() { return <SiteHeader /> }
function DashboardPreview() { return <div className="dashboard-preview" aria-label="School administrator dashboard preview"><aside className="dashboard-sidebar"><div className="school-badge"><span>DIS</span><small>school</small></div><button aria-label="Open dashboard menu">☰</button><nav><a className="active" href="#platform"><LayoutDashboard size={14} aria-hidden="true" /> <span>Dashboard</span></a><a href="#platform"><Database size={14} aria-hidden="true" /> <span>Management</span></a><a href="#platform"><UsersRound size={14} aria-hidden="true" /> <span>Users</span></a><a href="#platform"><ShieldCheck size={14} aria-hidden="true" /> <span>Assign</span></a><a href="#platform"><CalendarDays size={14} aria-hidden="true" /> <span>Attendance</span></a><a href="#platform"><ClipboardCheck size={14} aria-hidden="true" /> <span>CBT</span></a><a href="/contact"><Settings size={14} aria-hidden="true" /> <span>Settings</span></a></nav></aside><div className="dashboard-main"><div className="dashboard-topbar"><span className="search-line"><Search size={16} aria-hidden="true" /> Find Something . . .</span><span className="admin-chip"><strong>School Administrator</strong><small>admin</small></span></div><div className="dashboard-content"><p className="dashboard-kicker">Home <span>›</span> Admin</p><h2>Admin Dashboard</h2><div className="metric-grid"><article><span className="metric-icon"><CalendarDays size={23} /></span><span><small>2024/2025 Students</small><strong>188</strong><a href="#platform">View students →</a></span></article><article><span className="metric-icon"><UsersRound size={23} /></span><span><small>Total Students</small><strong>206</strong><a href="#platform">View students →</a></span></article><article><span className="metric-icon"><GraduationCap size={23} /></span><span><small>Teachers</small><strong>15</strong><a href="#platform">View staff →</a></span></article><article><span className="metric-icon"><UserRound size={23} /></span><span><small>Parents</small><strong>27</strong><a href="#platform">View parents →</a></span></article></div><div className="dashboard-lower"><article><h3>Quick stats</h3><p>See the counts that keep your school operations moving: students, teachers, parents, sessions, and performance.</p></article><article><h3>Tips</h3><p>Add new students, onboard teachers, invite parents, or manage school settings from the relevant workspace.</p></article></div></div></div></div> }
function Hero() { return <section className="hero section" id="top"><div className="hero-copy"><p className="eyebrow">CYFAMOD SMS <span>•</span> SCHOOL MANAGEMENT SYSTEM</p><h1>Control school operations<br /><em className="gradient-text">from one dashboard.</em></h1><p className="hero-rotator"><RotatingHeadline /></p><p className="hero-text">Centralise student records, staff, classes, attendance, results, CBT, reports, and daily academic workflows in a platform built for Nigerian schools.</p><div className="hero-actions"><Button>Book a product demo</Button><a className="text-link" href="#platform">View platform capabilities <Arrow /></a></div><div className="hero-proof"><strong>Admin dashboard first. Mobile apps connected.</strong><span>A complete school management system for administrators, staff, students, and parents.</span></div></div><div className="hero-visual"><DashboardPreview /></div></section> }
function WorkflowCard({ workflow }: { workflow: Workflow }) { const Icon = iconMap[workflow.key]; return <article className="workflow-card"><div className="workflow-heading"><span className="icon-box"><Icon size={20} /></span><div><span className="workflow-label">{workflow.key}</span></div></div><p className="workflow-description">{workflow.description}</p><ul>{workflow.rows.map(row => <li key={row}><ClipboardCheck size={15} />{row}</li>)}</ul><a href="/contact">Learn more <Arrow /></a></article> }
function Platform() { return <section className="platform section" id="platform"><div className="section-heading"><div><div className="section-kicker">THE CYFAMOD SMS PLATFORM</div><h2>Run your school with clarity. <em>Everything in one place.</em></h2></div><p>Manage everything centrally from the admin dashboard, then let the connected staff and student apps carry the right information into everyday work.</p></div><div className="workflow-grid">{workflows.map(workflow => <WorkflowCard key={workflow.key} workflow={workflow} />)}</div><div className="cbt-feature"><div><span className="section-kicker">FOR MODERN ASSESSMENT</span><h3>Computer Based Testing, without the complexity.</h3><p>Load assessments, manage candidate context, and keep academic records moving in one trusted workflow.</p><a className="button button-secondary" href="/contact">Talk to us about CBT <Arrow /></a></div><div className="cbt-screen"><img src={assets.staffResults} alt="Cyfamod staff result entry screen for selecting a class and subject" /></div></div></section> }
function Apps() { return <section className="apps section" id="apps"><div className="apps-heading"><div><div className="section-kicker">LIVE ON GOOGLE PLAY</div><h2>School tools that<br /><em>move with you.</em></h2></div><p>Dedicated mobile apps make Cyfamod SMS easier to use day to day, connected to the same school platform.</p></div><div className="app-showcase"><article className="app-card app-card-staff"><div className="app-meta"><img src={assets.staffIcon} alt="Cyfamod SMS Staff app logo" /><div><span>CYFAMOD-SMS</span><h3>Staff app</h3></div></div><p>Classes, students, and activity in one staff app.</p><img className="app-screen" src={assets.staffStudents} alt="Cyfamod staff app student search and filter screen" /></article><article className="app-card app-card-student"><div className="app-meta"><img src={assets.studentIcon} alt="Cyfamod SMS Student app logo" /><div><span>CYFAMOD-SMS</span><h3>Student app</h3></div></div><p>School information, results, and updates in one app.</p><img className="app-screen" src={assets.studentResults} alt="Cyfamod student app results download screen" /></article></div><div className="play-store-evidence"><article><div className="play-store-proof-heading"><div><strong>Cyfamod SMS Staff</strong><span>Google Play listing evidence</span></div></div><img className="play-store-proof-image" src={assets.playstoreStaff} alt="Google Play listing for Cyfamod SMS Staff" /></article><article><div className="play-store-proof-heading"><div><strong>Cyfamod SMS Student</strong><span>Google Play listing evidence</span></div></div><img className="play-store-proof-image" src={assets.playstoreStudent} alt="Google Play listing for Cyfamod SMS Student" /></article></div></section> }
function Partners() { return <section className="partners section" id="partners"><div className="partner-intro"><div className="section-kicker">CYFAMOD PARTNER PROGRAMME</div><h2>Refer schools.<br /><em>Earn commission.</em></h2><p>Cyfamod SMS is open to approved agents and corporate marketers who can bring the platform to school decision-makers. Every track is built around clear introductions, tracked conversions, and programme terms.</p><Button href="/partners" light>Explore partner tracks</Button></div><div className="partner-tracks"><article><span className="track-label">TRACK A</span><h3>Referral agent</h3><p>Share a referral code or link with school owners and administrators. Eligible school payments can qualify for percentage-based commission.</p><a href="/contact">Become a referral agent <Arrow /></a></article><article><span className="track-label">TRACK B</span><h3>Corporate marketer</h3><p>Find schools, arrange demos, manage follow-up, and support conversion into paying school customers.</p><a href="/contact">Apply as a corporate marketer <Arrow /></a></article></div></section> }
function SchoolMarquee() { return <section className="school-proof" aria-label="Cyfamod SMS school network"><div className="school-proof-heading"><span className="section-kicker">SCHOOL NETWORK</span><h2>Trusted by schools</h2></div><div className="school-marquee"><div className="school-marquee-inner"><div className="marquee-track">{[1, 2, 3].map(copy => <div className="marquee-group" key={copy}>{['abssmx.com.ng','al-hawa.com.ng','an-nur.com.ng','elbethelacademy.com','gdsc.com.ng','hamzawiyya.com.ng','hill-top.com.ng','querencia.com.ng','highpointschools.com','ellaschool.com'].map(name => <strong key={`${copy}-${name}`}>{name}</strong>)}</div>)}</div></div></div></section> }
function Footer() { return <SiteFooter /> }

export default function Page() { return <main><Header /><Hero /><section className="trust-strip"><div className="section trust-inner"><span className="trust-label">One connected school system</span><span>ADMINISTRATION</span><span>STAFF</span><span>STUDENTS</span><span>RESULTS</span><span>CBT</span></div></section><section className="problem section"><div className="section-kicker">THE EVERYDAY PROBLEM</div><div className="problem-grid"><h2>Replace scattered records with <em>centralised school control.</em></h2><div><p>Many schools still manage records, attendance, payments, results, and parent communication across notebooks, spreadsheets, WhatsApp messages, and manual reports.</p><p>Cyfamod SMS brings those daily operations into one organised school management system so leaders can work from accurate information.</p><a className="text-link" href="#platform">See what is connected <Arrow /></a></div></div></section><Platform /><Apps /><Partners /><SchoolMarquee /><section className="final-cta section" id="contact"><div><div className="section-kicker">BOOK A DEMO</div><h2>Manage school operations<br /><em>from one platform.</em></h2><p>See the admin dashboard, staff app, student app, CBT, results, attendance, and reports working together in one connected system.</p></div><div className="cta-panel"><span>Request a guided product walkthrough.</span><Button>Book a product demo</Button><small>Built for Nigerian school operations.</small></div></section><Footer /></main> }
